create table "public"."players" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "color" text,
    "user_id" uuid
);


alter table "public"."players" enable row level security;

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."players" add constraint "players_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."players" validate constraint "players_user_id_fkey";


